apiVersion: v2
name: trigger
description: The official Trigger.dev Helm chart
type: application
version: 4.0.0-beta.4
appVersion: v4.0.0-v4-beta.21
home: https://trigger.dev
sources:
  - https://github.com/triggerdotdev/trigger.dev
keywords:
  - trigger
  - workflow
  - background-jobs
  - job-scheduler
  - task-queue
  - automation
annotations:
  category: Development
