name: ðŸš€ Publish Trigger.dev Docker

on:
  repository_dispatch:
  workflow_call:
    inputs:
      image_tag:
        description: The image tag to publish
        required: true
        type: string
  push:
    branches:
      - main
    tags:
      - "v.docker.*"
      - "build-*"
    paths:
      - ".github/actions/**/*.yml"
      - ".github/workflows/publish.yml"
      - ".github/workflows/typecheck.yml"
      - ".github/workflows/unit-tests.yml"
      - ".github/workflows/e2e.yml"
      - ".github/workflows/publish-webapp.yml"
      - ".github/workflows/publish-worker.yml"
      - "packages/**"
      - "!packages/**/*.md"
      - "!packages/**/*.eslintrc"
      - "internal-packages/**"
      - "apps/**"
      - "!apps/**/*.md"
      - "!apps/**/*.eslintrc"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - "turbo.json"
      - "docker/Dockerfile"
      - "docker/scripts/**"
      - "tests/**"

permissions:
  id-token: write
  packages: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  AWS_REGION: us-east-1

jobs:
  typecheck:
    uses: ./.github/workflows/typecheck.yml
    secrets: inherit

  units:
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit

  publish-webapp:
    needs: [typecheck]
    uses: ./.github/workflows/publish-webapp.yml
    secrets: inherit
    with:
      image_tag: ${{ inputs.image_tag }}

  publish-worker:
    needs: [typecheck]
    uses: ./.github/workflows/publish-worker.yml
    secrets: inherit
    with:
      image_tag: ${{ inputs.image_tag }}

  publish-worker-v4:
    needs: [typecheck]
    uses: ./.github/workflows/publish-worker-v4.yml
    secrets: inherit
    with:
      image_tag: ${{ inputs.image_tag }}
