name: "âš’ï¸ Publish Worker"

on:
  workflow_call:
    inputs:
      image_tag:
        description: The image tag to publish
        type: string
        required: false
        default: ""
  push:
    tags:
      - "infra-dev-*"
      - "infra-test-*"
      - "infra-prod-*"

permissions:
  packages: write
  contents: read

jobs:
  build:
    strategy:
      matrix:
        package: [coordinator, docker-provider, kubernetes-provider]
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - name: â¬‡ï¸ Checkout git repo
        uses: actions/checkout@v4

      - name: ğŸ“¦ Get image repo
        id: get_repository
        run: |
          if [[ "${{ matrix.package }}" == *-provider ]]; then
            provider_type=$(echo "${{ matrix.package }}" | cut -d- -f1)
            repo=provider/${provider_type}
          else
            repo="${{ matrix.package }}"
          fi
          echo "repo=${repo}" >> "$GITHUB_OUTPUT"

      - id: get_tag
        uses: ./.github/actions/get-image-tag
        with:
          tag: ${{ inputs.image_tag }}

      - name: ğŸ‹ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ..to avoid rate limits when pulling images
      - name: ğŸ³ Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ğŸš¢ Build Container Image
        run: |
          docker build -t infra_image -f ./apps/${{ matrix.package }}/Containerfile .

      # ..to push image
      - name: ğŸ™ Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ™ Push to GitHub Container Registry
        run: |
          docker tag infra_image "$REGISTRY/$REPOSITORY:$IMAGE_TAG"
          docker push "$REGISTRY/$REPOSITORY:$IMAGE_TAG"
        env:
          REGISTRY: ghcr.io/triggerdotdev
          REPOSITORY: ${{ steps.get_repository.outputs.repo }}
          IMAGE_TAG: ${{ steps.get_tag.outputs.tag }}

      # - name: ğŸ™ Push 'v3' tag to GitHub Container Registry
      #   if: steps.get_tag.outputs.is_semver == 'true'
      #   run: |
      #     docker tag infra_image "$REGISTRY/$REPOSITORY:v3"
      #     docker push "$REGISTRY/$REPOSITORY:v3"
      #   env:
      #     REGISTRY: ghcr.io/triggerdotdev
      #     REPOSITORY: ${{ steps.get_repository.outputs.repo }}
