name: "âš’ï¸ Publish Worker (v4)"

on:
  workflow_call:
    inputs:
      image_tag:
        description: The image tag to publish
        type: string
        required: false
        default: ""
  push:
    tags:
      - "re2-test-*"
      - "re2-prod-*"

permissions:
  id-token: write
  packages: write
  contents: read

jobs:
  # check-branch:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Fail if re2-prod-* is pushed from a non-main branch
  #       if: startsWith(github.ref_name, 're2-prod-') && github.base_ref != 'main'
  #       run: |
  #         echo "ğŸš« re2-prod-* tags can only be pushed from the main branch."
  #         exit 1
  build:
    # needs: check-branch
    strategy:
      matrix:
        package: [supervisor]
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - name: ğŸ­ Setup Depot CLI
        uses: depot/setup-action@v1

      - name: â¬‡ï¸ Checkout git repo
        uses: actions/checkout@v4

      - name: ğŸ“¦ Get image repo
        id: get_repository
        run: |
          if [[ "${{ matrix.package }}" == *-provider ]]; then
            provider_type=$(echo "${{ matrix.package }}" | cut -d- -f1)
            repo=provider/${provider_type}
          else
            repo="${{ matrix.package }}"
          fi
          echo "repo=${repo}" >> "$GITHUB_OUTPUT"

      - name: "#ï¸âƒ£ Get image tag"
        id: get_tag
        uses: ./.github/actions/get-image-tag
        with:
          tag: ${{ inputs.image_tag }}

      - name: ğŸ“› Set tags to push
        id: set_tags
        run: |
          ref_without_tag=ghcr.io/triggerdotdev/${{ steps.get_repository.outputs.repo }}
          image_tags=$ref_without_tag:${{ steps.get_tag.outputs.tag }}

          # if tag is a semver, also tag it as v4
          if [[ "${{ steps.get_tag.outputs.is_semver }}" == true ]]; then
            # TODO: switch to v4 tag on GA
            image_tags=$image_tags,$ref_without_tag:v4-beta
          fi

          echo "image_tags=${image_tags}" >> "$GITHUB_OUTPUT"

      - name: ğŸ™ Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ³ Build image and push to GitHub Container Registry
        uses: depot/build-push-action@v1
        with:
          file: ./apps/${{ matrix.package }}/Containerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.get_tag.outputs.tag }}
          # push: true
