name: Vouch - Manage by Issue

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write

jobs:
  manage:
    runs-on: ubuntu-latest
    if: >-
      contains(github.event.comment.body, 'vouch') ||
      contains(github.event.comment.body, 'denounce') ||
      contains(github.event.comment.body, 'unvouch')
    steps:
      - uses: actions/checkout@v4
      - uses: mitchellh/vouch/action/manage-by-issue@main
        with:
          comment-id: ${{ github.event.comment.id }}
          issue-id: ${{ github.event.issue.number }}
        env:
          GH_TOKEN: ${{ github.token }}
